export const teamOptions = [
    { group: 'Espanha', value: 'Real Madrid' },
    { group: 'Espanha', value: 'Barcelona' },
    { group: 'Espanha', value: 'Atlético de Madrid' },
    { group: 'Espanha', value: 'Sevilla' },
    { group: 'Espanha', value: 'Real Sociedad' },
    { group: 'Espanha', value: 'Villarreal' },
    { group: 'Espanha', value: 'Girona' },
    { group: 'Inglaterra', value: 'Manchester City' },
    { group: 'Inglaterra', value: 'Arsenal' },
    { group: 'Inglaterra', value: 'Liverpool' },
    { group: 'Inglaterra', value: 'Manchester United' },
    { group: 'Inglaterra', value: 'Chelsea' },
    { group: 'Inglaterra', value: 'Tottenham' },
    { group: 'Inglaterra', value: 'Aston Villa' },
    { group: 'Inglaterra', value: 'Newcastle United' },
    { group: 'Itália', value: 'Inter de Milão' },
    { group: 'Itália', value: 'AC Milan' },
    { group: 'Itália', value: 'Juventus' },
    { group: 'Itália', value: 'Napoli' },
    { group: 'Itália', value: 'AS Roma' },
    { group: 'Itália', value: 'Atalanta' },
    { group: 'Alemanha', value: 'Bayern de Munique' },
    { group: 'Alemanha', value: 'Borussia Dortmund' },
    { group: 'Alemanha', value: 'Bayer Leverkusen' },
    { group: 'Alemanha', value: 'RB Leipzig' },
    { group: 'França', value: 'PSG' },
    { group: 'França', value: 'Marseille' },
    { group: 'França', value: 'Monaco' },
    { group: 'França', value: 'Lille' },
    { group: 'Outras Ligas', value: 'Benfica' },
    { group: 'Outras Ligas', value: 'FC Porto' },
    { group: 'Outras Ligas', value: 'Sporting CP' },
    { group: 'Outras Ligas', value: 'Ajax' },
    { group: 'Outras Ligas', value: 'PSV Eindhoven' },
    { group: 'Outras Ligas', value: 'Boca Juniors' },
    { group: 'Outras Ligas', value: 'River Plate' },
    { group: 'Outras Ligas', value: 'Inter Miami' },
    { group: 'Outras Ligas', value: 'Al-Nassr' },
    { group: 'Outras Ligas', value: 'Al-Hilal' },
];

export const platformOptions = [
    { value: 'PS5' },
    { value: 'Xbox Series X/S' },
    { value: 'PC' }
];
